version: "2.4"
services: 
  client:

    image: wwioiww0514/client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    mem_limit: 128m

  nginx_proxy:
    #server 재시작 정책 
    restart: always
    image: wwioiww0514/nginx_proxy
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - client
      - api
      
  api:
    image: wwioiww0514/api
    container_name: app_api
    volumes:
      - /app/node_modules
      - ./backend:/app
    enviroment:
      MYSQL_HOST : ${{secrets.DOCKER_DB_HOST}}
      MYSQL_USER : ${{secrets.DOCKER_DB_USER}}
      MYSQL_ROOT_PASSWORD: ${secrets.DOCKER_DB_PASSWORD}
      MYSQL_DATABASE: ${{secrets.DOCKER_DB_USE}}
      MYSSQL_PORT: 3306
    mem_limit: 128m
  