version: "3"

services: 
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    stdin_open: true
    

  nginx_proxy:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx_proxy
    ports:
      - "3000:80"
    

  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./api
    container_name: app_api
    volumes:
      - /app/node_modules
      - ./api:/app
  
  db:
    build: ./db
    restart: unless-stopped
    container_name: app_db
    ports:
      - "3307:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql
      - ./db/sqls/:/docker-entrypoint-initdb.d/
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    environment:
      MYSQL_ROOT_PASSWORD: '123'
      MYSQL_DATABASE: multi




  