name: react-in-docker

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - name:  Build the docker-compose image
          run: docker-compose up -d
        