# 베이스로 ubuntu 혹은 centos등을 사용해도 되지만
# hello를 출력하는 간단한 앱을 만들것이기 때문에
# 사이즈가 작은 alpine 베이스 이미지를 사용
FROM alpine 

CMD ["echo","hello"]

# 도커 파일에 입력된 것들이 도커 클라이언트에
# 전달해 도커 서버가 인식하게 한다.
# 그러기 위해서 사용되는 명령어
# -> docker build ./ or docker build .

# Dockerfile -> Docker Client -> Docker Server
# Docker Image