name: react-in-docker

on: 
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps: 

      - name: Checkout
        uses: actions/checkout@v3
     
      
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }} 
          password: ${{ secrets.DOCKER_PASSWORD }} 
      

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"
     
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-in-aws
          environment_name: Docker-in-aws-env
          existing_bucket_name: ${{ secrets.AWS_BUCKET_NAME }}
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: docker-in-aws/Dockerrun.aws.json
          



      