name: react-in-docker

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  CI-CD:
    runs-on: ubuntu-latest  
    steps: 
      - uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}  
    
      - name: Docker build & push to dev
        run: |
          cd react-in-docker
          docker build -f Dockerfile.dev -t ${{ secrets.DOCKER_USER}}/react_in_nginx .
          docker run ${{ secrets.DOCKER_USER }}/react_in_docker_dev  npm run test -- --coverage
          echo "TEST Success"

      