name: react-in-docker

on: 
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps: 
    
      - uses: actions/checkout@v3
     
      - name: Docker.dev image build & test
        run: |
          cd react-in-docker
          docker build -f Dockerfile.dev -t ${{ secrets.DOCKER_USER}}/react_in_docker_dev .
          docker run -e CI=true  ${{ secrets.DOCKER_USER }}/react_in_docker_dev  npm run test -- --coverage
          echo "TEST Success"

      